Listen 3000

# Global Passenger settings
PassengerRoot /usr/local/share/gems/gems/passenger-6.1.0
PassengerDefaultRuby /usr/bin/ruby
PassengerMaxPoolSize 6
PassengerMinInstances 1
PassengerPreStart http://127.0.0.1:3000/

<VirtualHost *:3000>
    ServerName 127.0.0.1
    DocumentRoot "/opt/redmine/public"

    CustomLog logs/redmine_access.log combined
    ErrorLog logs/redmine_error.log
    LogLevel warn

    PassengerAppEnv production

    <Directory "/opt/redmine/public">
        Options -MultiViews
        Require all granted
        AllowOverride all
    </Directory>
</VirtualHost>
